config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :claims do
    collection do
      get :success
      post :insurance_estimate
      post :extract # mock
    end

    member do
      get :export
      post :review
      resources :charges, only: [:new, :create]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/checkout', to: 'home#checkout'
  get '/additional_info', to: 'home#additional_info'

  get '/revamp', to: 'home#revamp'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  def revamp; end
end

app/views/home/_banner.html.erb
<div class="bg-white">
  <div class="row m-0">
    <div class="col-md-6">
      <div class="position-relative">
        <video controls class="video_modal w-100">
          <source src="media/clariclaim-v1.mp4" type="video/mp4">
        </video>
        <div class="position-absolute w-100 t-100">
          <div class="row d-none">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <h2>$443 Billion</h2>
              <h3>Insurance Claims Yearly</h3>
              <h5>Learn how we can maximize your claim with our simple 3 step process. Upload your estimate today and be at ease knowing we?ve got your coverageLearn how we can maximize your claim with our simple 3 step process. Upload your estimate today and be at ease knowing we?ve got your coverage</h5>
            </div>
            <div class="col-md-2"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row mt-3">
        <div class="col-md-2"></div>
        <div class="col-md-8 col-12">
          <div>
            <%= form_tag(claims_path, { method: :post, multipart: true }) do %>
              <input id="website" name="website" type="text" value=""><!-- Leave for security protection, read docs for details -->
              <div id="middle-wizard" class="bg-white p-3">
                <%= render 'steps/form_step_1' %>
                <%= render 'steps/form_step_2' %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="site-footer">
  <div class="footer-widgets">
    <div class="container">
      <div class="row gx-lg-5">
        <div class="col-lg-4 pr-lg-10">
          <div class="footer-widget footer-widget-1">
            <h1 class="mb-3 text-white">SANAT</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row gx-lg-6">
        <div class="col-lg-5">
          <form class="mt-3" id="contact-form" method="post" action="assets/php/contact.php">
            <div class="form-group row gx-0">
              <div class="col-lg-7 col-md-8">
                <input class="form-control bg-white border-0" id="form_name" type="text" name="fname" placeholder="Email" required="">
              </div>
              <div class="col-lg-4 col-md-3"><a class="btn btn-school-yellow rounded-0 border-0 d-block" href="#">Subscribe</a></div>
            </div>
          </form>
        </div>
        <div class="col-lg-7">
          <div class="row gx-lg-5">
            <div class="col-lg-3 col-md-6 col-12 mt-lg-0 mt-md-5 mt-5">
              <div class="footer-widget footer-widget-2">
                <ul>
                  <li><a href="page-contact-us.html">About Us</a></li>
                  <li><a href="page-contact-us.html">Location</a></li>
                  <li><a href="page-contact-us.html">Case Studies</a></li>
                  <li><a href="page-contact-us.html">Contact</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-12 mt-lg-0 mt-md-5 mt-0">
              <div class="footer-widget footer-widget-2">
                <ul>
                  <li><a href="index.html">Manufacturing </a></li>
                  <li><a href="blog.html">Certificates</a></li>
                  <li><a href="page-services.html">Platform</a></li>
                  <li><a href="page-about-us.html">Faq's</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-12">
              <div class="footer-widget footer-widget-2">
                <ul>
                  <li><a href="index.html">Careers</a></li>
                  <li><a href="blog.html">For Media</a></li>
                  <li><a href="page-services.html">Invester Relation</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-12">
              <div class="footer-widget footer-widget-2">
                <ul>
                  <li><a href="index.html">Client Portal </a></li>
                  <li><a href="blog.html">Legal &amp; Privacy</a></li>
                  <li><a href="page-services.html">Blog</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom-area">
    <div class="container">
      <div class="row gx-5 align-items-center">
        <div class="col-lg-6 col-md-6">
          <div class="footer-widget">
            <p class="m-md-0">© 2021 Energetic Themes • All Rights Reserved</p>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="text-right">
            <ul class="list-unstyled list-inlinetrue">
              <li class="list-inline-item border-padding border border-1 rounded-circle mr-4"><a href="#"><i class="fab fa-linkedin-in icon"></i></a></li>
              <li class="list-inline-item border-padding border border-1 rounded-circle mr-4"><a href="#"><i class="fab fa-facebook-square icon"></i></a></li>
              <li class="list-inline-item border-padding border border-1 rounded-circle mr-4"><a href="#"><i class="fab fa-twitter icon"></i></a></li>
              <li class="list-inline-item border-padding border border-1 rounded-circle mr-4"><a href="#"><i class="fab fa-instagram icon"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<div id="loader_form">
  <div data-loader="circle-side-2"></div>
</div><!-- /Loader_form -->

<header>
    <div id="logo_home">
        <img src="img/logo_sized.png" alt="logo" />
        <h1><a href="/" title="Clariclaim">Clariclaim - Request a claim for every type of companies</a></h1>
    </div>

    <a id="menu-button-mobile" class="cmn-toggle-switch cmn-toggle-switch__htx" href="javascript:void(0);"><span>Menu mobile</span></a>
    <nav class="main_nav">
        <ul class="nav nav-tabs">
            <li><a href="#tab_1" data-toggle="tab">Clariclaim Report</a></li>
            <li><a href="#tab_2" data-toggle="tab">About</a></li>
            <li><a href="#tab_3" data-toggle="tab">Contact</a></li>
            <li><a href="#tab_3" data-toggle="tab">Resource</a></li>
        </ul>
    </nav>
</header><!-- /header -->

app/views/home/_intro.html.erb
<div class="intro_txt animated fadeInUp">
    <h2>INSURANCE CLAIMS ARE CONFUSING, GET THE CLARIFICATION YOU NEED.</h2>
    <p>Replacement Cost? Proof of loss? Remove and Reset? No matter what type of loss you suffered, We Can help.</p>
</div><!-- /intro_txt -->

<div id="claim-button-mobile-container">
  <button id="claim-button-mobile" class="btn_1" type="button" name="button" onclick="openClaimForm()">
    ClariClaim Report
  </button>
</div>

<video id="my-video" class="video" loop muted autoplay playsinline>
  <source src="media/clariclaim-video.mp4" type="video/mp4">
  <source src="media/clariclaim-video.ogv" type="video/ogg">
  <source src="media/clariclaim-video.webm" type="video/webm">
</video><!-- /video -->
<div class="video_fallback"></div>

<div class="layer"></div><!-- /mask -->

<script type="text/javascript">
  function openClaimForm() {
    $Mc = $('#main_container');
    $Layer = $('.layer');
    $Mc.addClass("show_container")
    $Layer.addClass("layer-is-visible")
    $('#tab_1').addClass("active show");
  }
</script>

app/views/home/_intro_new.html.erb
<!-- <div class="container margin_60_35" style="margin-top: 126px;">
  <div class="row justify-content-center">
    <div class="row magnific add_bottom_15">
      <div class="col-md-6">
        <p>
          <a href="media/clariclaim-v1.mp4" class="video_modal" title="Play video!">
            <img src="media/clariclaim.png" alt="" class="img-fluid">
          </a>
        </p>
      </div>
      <div class="col-md-6" style="text-align: center;">
        <p style="padding:25px; ">
          </p><h3 style="padding:5px">Clarify Today</h3>
          <p><a href="#0" class="btn_outline" onclick="openClaimForm()">Start Now</a> </p>
        <p></p>
      </div>
    </div>
  </div>
</div> -->

<script type="text/javascript">
  function openClaimForm() {
    $Mc = $('#main_container');
    $Layer = $('.layer');
    $Mc.addClass("show_container")
    $Layer.addClass("layer-is-visible")
    $('#tab_1').addClass("active show");
  }
</script>

app/views/home/_stage_4.html.erb
<div class="bg-white">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= form_tag(claims_path, { method: :post, multipart: true }) do %>
        <div class="step" id="step3">
          <label>Stage 3</label>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" name="claim[phone]" class="required form-control" placeholder="Phone">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <div class="styled-select">
                  <select class="required" name="claim[contact_preference]">
                      <option value="" selected>Select your contact preference</option>
                      <option value="phone">Phone</option>
                      <option value="email">Email</option>
                  </select>
                </div>
              </div>
            </div><!-- /col-sm-6 -->

            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" name="claim[address]" class="required form-control" placeholder="Address">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" name="claim[city]" class="required form-control" placeholder="City">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" name="claim[state]" class="required form-control" placeholder="State">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" name="claim[zipcode]" class="required form-control" placeholder="Zipcode">
              </div>
            </div><!-- /col-sm-6 -->
          </div><!-- /row -->
          <button type="submit" name="" class="submit">submit</button>
        </div>
      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/home/additional_info.html.erb
<%= render "header" %>
<%= render "intro_new" %>
<%= render 'stage_4' %>
<%= render "main" %>
<%= render "footer" %>

app/views/home/checkout.html.erb
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button pull-right"
  data-key="<%= Rails.application.credentials.stripetest[:pk] %>"
  data-email="test@johndoe.com"
  data-label="Pay">
</script>

app/views/home/index.html.erb
<%= render "header" %>
<%= render "intro_new" %>
<%# render "intro" %>
<%= render "main" %>
<%= render "footer" %>

app/views/home/old_footer.html.erb
<div id="additional_links">
    <ul>
        <li>© <%= Time.now.year %> Clariclaim</li>
        <li><a href="#0" data-toggle="modal" data-target="#policy-txt">Privacy Policy</a></li>
        <li><a href="#0" data-toggle="modal" data-target="#terms-txt">Terms of Use</a></li>
        <li><a href="#tab_3" onclick="showContact()">Contact</a></li>
    </ul>
</div><!-- /add links -->

<%= render "modals/modal" %>

<!-- SCRIPTS -->
<!-- Jquery-->
<script src="js/jquery-3.5.1.min.js"></script>
<!-- Common script -->
<script src="js/common_scripts_min.js"></script>
<!-- Theme script -->
<script src="js/file-validator.js"></script>
<script src="js/functions_with_upload.js"></script>

<!-- Google map -->
<script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTnrAc18j5zHsTD5z-wA1SNqJ0ExJfRH8&callback=initAutocomplete&libraries=places&v=weekly"
  async
></script>

<script src="js/mapmarker.jquery.js"></script>
<script src="js/mapmarker_func.jquery.js"></script>

<script type="text/javascript">
  function showContact() {
    $Mc = $('#main_container');
    $Layer = $('.layer');
    $Mc.addClass("show_container")
    $Layer.addClass("layer-is-visible")
    $('#tab_3').addClass("active show");
  }
</script>

app/views/home/revamp.html.erb
NEW Homepage updates here