config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :claims do
    collection do
      get :success
      post :insurance_estimate
      post :extract # mock
    end

    member do
      get :export
      post :review
      resources :charges, only: [:new, :create]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/checkout', to: 'home#checkout'
  get '/additional_info', to: 'home#additional_info'

  get '/revamp', to: 'home#revamp'
end

app/models/claim.rb
class Claim < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  enum contact_preference: { phone: 0, email: 1 }

  belongs_to :package

  mount_uploader :declarations_page,  PdfUploader
  mount_uploader :insurance_estimate, PdfUploader

  validate :loss_date_cannot_be_in_the_future

  after_initialize :set_default_json_data

  delegate :name, to: :package, prefix: true, allow_nil: true

  attribute :full_name

  def loss_type_formatted
    if loss_type_desc.present?
      "#{loss_type} - #{loss_type_desc}"
    else
      loss_type
    end
  end

  def addons
    Package.where(id: addons_ids)
  end

  def addons_ids
    addons_data.fetch('ids') rescue []
  end

  def update_addons(ids)
    self.addons_data['ids'] = ids.kind_of?(Array) ? ids : [ids]
    self.save!
  end

  def supplemental_claims
    addons_data.fetch('supplemental_claims') rescue []
  end

  def supplemental_rooms
    supplemental_claims.fetch('rooms') rescue []
  end

  def extract!
    require 'uri'
    require 'net/http'
    doc = insurance_estimate
    doc.cache_stored_file! if !doc.cached?

    uri = URI(ENV['OCR_SERVICE_URL'])
    https = Net::HTTP.new(uri.host, uri.port)
    https.read_timeout = 1_000
    # https.use_ssl = true

    request = Net::HTTP::Post.new(uri.path)
    request["Content-Type"] = "application/json"
    request.body = {
      pdf_path: doc.current_path.split("pdfparserapi")[1]
    }.to_json

    response = https.request(request)
    update_columns(meta: JSON.parse(response.body))
  end

  def send_sms(message, from=nil)
    require 'rubygems'
    require 'twilio-ruby'

    account_sid = 'AC38d806a071041dec24bcc491b6ed7e1c'
    auth_token = '[AuthToken]'
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    @client.messages.create(
               body: message,
               to: phone_with_codes
             )

    puts message.sid
  end

  def phone_with_codes
    if !loss_location.include?("+")
      return phone.prepend("+1") if loss_location.include?("US")
    end

    phone
  end

  def meta_claim_number
    meta['data']['claim_number'] rescue ''
  end

  def meta_policy_number
    meta['data']['policy_number'] rescue ''
  end

  def meta_loss_type
    type_of_loss = meta['data']['type_of_loss'] rescue ''

    type_of_loss.present? ? type_of_loss : loss_type
  end

  def meta_insured
    meta['data']['insured'] rescue ''
  end

  def meta_estimator
    meta['data']['estimator'] rescue ''
  end

  def review_claim_number
    review_data['claim_number'] rescue meta_claim_number
  end

  def review_policy_number
    review_data['policy_number'] rescue meta_policy_number
  end

  def review_loss_type
    review_data['loss_type'] rescue meta_loss_type
  end

  def review_loss_date
    review_data['loss_date'] rescue loss_date
  end

  def insured
    "#{first_name} #{last_name}"
  end

  private

  def loss_date_cannot_be_in_the_future
    if loss_date.present? && loss_date > Date.today
      errors.add(:loss_date, "can't be in the future")
    end
  end

  def set_default_json_data
    addons_data = {} if addons_data.nil?
    review_data = {} if review_data.nil?
  end

  def full_name= value
    names = value.split(' ')
    if names.length > 1
      self.first_name = names[0]
      self.last_name  = value.from(names[0].length + 1)
    else
      self.first_name = ''
      self.last_name  = names[0]
    end
  end
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def create
    tparams = claim_params
    @claim = Claim.new(claim_params)
    full_name = params[:claim][:full_name]
    names = full_name.split(' ')
    if names.length > 1
      tparams[:first_name] = names[0]
      tparams[:last_name]  = full_name.from(names[0].length + 1)
    else
      tparams[:first_name] = ''
      tparams[:last_name]  = names[0]
    end

    respond_to do |format|
      if @claim.save
        ZohoClaimCreator.new.perform(tparams)
        @claim.update_columns(
          addons_data: addons_params,
          loss_location_meta: loss_location_meta_params
        )

        ExtractWorker.perform_async(@claim.id)

        session = Stripe::Checkout::Session.create({
          line_items: [{
            price: 'price_1JXxDwC7nkluOhqwdPInLrH6',
            quantity: 1,
          }],
          payment_method_types: [
            'card',
          ],
          mode: 'payment',
          success_url: domain + "additional_info?claim_id=#{@claim.id}",
          cancel_url: domain + '/claims/cancel',
        })

        format.html { redirect_to session.url, status: 303 }
        # format.html { redirect_to success_claims_path, notice: "Claim was successfully created." }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  def success; end

  def insurance_estimate
    FileUtils.cp(params[:file].tempfile.path, "#{Rails.root}/pdfparserapi/pdfs/")

    temp_filename = params[:file].tempfile.path.split("/").last

    require 'uri'
    require 'net/http'

    uri = URI(ENV['OCR_SERVICE_URL'])
    https = Net::HTTP.new(uri.host, uri.port)
    https.read_timeout = 1_000

    request = Net::HTTP::Post.new(uri.path)
    request["Content-Type"] = "application/json"
    request.body = {
      pdf_path: "/pdfs/#{temp_filename}"
    }.to_json

    response = https.request(request)
    budget = JSON.parse(response.body)['data']['RCV'] rescue nil

    render json: { data: Package.find_package(budget).try(:id), status: :ok }
  end

  def extract
    puts "extracted"
    render json: {
      "RCV": "40433.49",
      "business": "(508) 450-0507 (508) 450-0507",
      "claim_number": "TPPT84",
      "company": "",
      "email": "tim.martino@seltser.com espalding@mapfreusa.com espalding@mapfreusa.com",
      "estimate": "BILLY_SILVA",
      "estimator": "Erin Spalding",
      "insured": "BILLY SILVA",
      "phone": "",
      "policy_number": "BHMVBV",
      "type_of_loss": "Water Damage"
    }
  end

  def export
    @claim = Claim.find_by(id: params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "pdf"   # Excluding ".pdf" extension.
      end
    end

    # pdf = Prawn::Document.new()
    # pdf.text "SAMPLE DOC HERE"
    # pdf.text "Claim Number: FLP6842"
    # pdf.text "Policy Number: FLP6842"
    # pdf.text "Type of Loss: Water Damage"
    # pdf.text "Date of Loss:	7/9/2021 12:00 AM"
    # send_data pdf.render, filename: "claim-#{Time.now}.pdf", type: "application/pdf"
  end

  def review
    @claim = Claim.find_by(id: params[:id])
    @claim.update(review_data: params[:data])

    redirect_to export_claim_url(format: :pdf)
  end

  private
    # Only allow a list of trusted parameters through.
    def claim_params
      params.require(:claim).permit(
        :loss_type, :loss_date, :loss_type_desc, :property_type,
        :other_unit_affected, :loss_location, :loss_location_start,
        :loss_location_point, :declarations_page, :insurance_estimate,
        :damage_outside_insurance, :package_id, :addons_data, :first_name,
        :last_name, :address, :city, :state, :zipcode, :phone, :email,
        :contact_preference
      )
    end

    def addons_params
      ids = params[:claim].slice(:addons_101, :addons_102, :addons_103)
                  .values.compact.map(&:to_i)
      rooms = []
      params[:claim][:room_name].each_with_index do |name, index|
        rooms << {
          name: name,
          dimension: params[:claim][:room_dimension][index]
        }
      end if ids.include?(101)

      {
        ids: ids,
        supplemental_claims: {
          rooms: rooms
        }
      }
    end

    def loss_location_meta_params
      JSON.parse(params[:claim][:loss_location_meta])
    end

    def domain
      Rails.env.production? ? 'https://clariclaim.com/' : 'http://localhost:3000/'
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/admin/claims/_export.html.erb
<form novalidate="novalidate">
  <center><b>Review Claim Data</b></center>
  <br>
  <fieldset class="inputs">
    <ol>
      <li class="input stringish">
        <label class="label">Claim Number</label>
        <input maxlength="255" type="text" value="<%= claim&.meta['data']['claim_number'] rescue '' %>" name="claim[claim_number]">
      </li>
      <li class="input stringish">
        <label class="label">Policy Number</label>
        <input maxlength="255" type="text" value="<%= claim&.meta['data']['policy_number'] rescue '' %>" name="claim[policy_number]">
      </li>
      <li class="input stringish">
        <label class="label">Type of Loss</label>
        <input maxlength="255" type="text" value="<%= claim&.meta['data']['type_of_loss'] rescue '' %>" name="claim[type_of_loss]">
      </li>
      <li class="input">
        <label class="label">Date of Loss</label>
        <input type="date" style="width: fit-content;" value="<%= claim&.loss_date rescue '' %>" name="claim[loss_date]">
      </li>
    </ol>
  </fieldset>

  <center><b>Review Items</b></center>
  <br>
  <fieldset class="inputs">
    <ol>
      <li class="input stringish">
        <label class="label">Item Name</label>
        <input maxlength="255" type="text" value="">
        <br>
        <br>
        <fieldset class="inputs">
          <ol>
            <li class="input stringish">
              <label class="label">Description</label>
              <input maxlength="255" type="text" value="">
            </li>
            <li class="input stringish">
              <label class="label">Quantity</label>
              <input maxlength="255" type="text" value="">
            </li>
            <li class="input stringish">
              <label class="label">Unit Price</label>
              <input maxlength="255" type="text" value="">
            </li>
            <li class="input stringish">
              <label class="label">ACV</label>
              <input maxlength="255" type="text" value="">
            </li>
            <li class="input stringish">
              <label class="label">RCV</label>
              <input maxlength="255" type="text" value="">
            </li>
          </ol>
        </fieldset>
      </li>
    </ol>
  </fieldset>
  <div class="buttons" style="float: right;">
    <input type="button" name="add" value="Add New Item" data-disable-with="Add New Item">
  </div>


<!-- <fieldset class="actions"><ol><li class="action input_action " id="admin_user_submit_action"><input type="submit" name="commit" value="Update Admin user" data-disable-with="Update Admin user"></li><li class="cancel"><a href="/admin/admin_users">Cancel</a></li></ol></fieldset> -->

</form>

<br><br><br>
<hr>
<br><br><br>
<div class="buttons" style="float: right;">
  <a href="<%= export_claims_url(format: :pdf) %>" target="_blank" >
    <input type="submit" name="commit" value="Export" data-disable-with="Export">
  </a>
</div>


<script type="text/javascript">

</script>

app/views/admin/claims/_maps.html.erb
<iframe
  width="100%"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  src='<%= "https://www.google.com/maps/embed/v1/streetview?key=AIzaSyDTnrAc18j5zHsTD5z-wA1SNqJ0ExJfRH8&location=#{location_point}" %>'>
</iframe>

<div style="float:right">
  Or <a href='<%= "https://maps.google.com/?q=#{location}&zoom=14" %> target="_blank"'> show on maps</a> if Street View unavailable.
</div>

app/views/admin/claims/_payment.html.erb
Link payment for this claim:

<%= link_to new_charge_url(token: '1bb6ezimrz'), new_charge_path(token: '1bb6ezimrz'), target: '_blank' %>

app/views/admin/claims/_review.html.erb
<form novalidate="novalidate">
  <center><b>Review Items</b></center>
  <br>
  <fieldset class="inputs" style="padding: 20px;">
    <ol>
      <li class="input stringish">
        <label class="label">Item Name</label>
        <input id="item-name" maxlength="30" type="text" value="Room: (living Room)">
        <br>
        <br>
        <fieldset class="inputs" style="padding: 12px; margin: 0 30px;">
          <ol>
            <li class="input stringish">
              <label class="label">Description</label>
              <input id="item-desc" maxlength="30" type="text" value="Remove and Reset Contents">
            </li>
            <li class="input stringish">
              <label class="label">Quantity</label>
              <input id="item-quantity" maxlength="9" type="text" value="">
            </li>
            <li class="input stringish">
              <label class="label">Unit</label>
              <input id="item-unit" maxlength="9" type="text" value="1">
            </li>
            <li class="input stringish">
              <label class="label">Price</label>
              <input id="item-price" maxlength="9" type="text" value="">
            </li>
          </ol>
        </fieldset>
      </li>
    </ol>
    <div class="buttons" style="float: right;">
      <input type="button" name="add" value="Add New Item" data-disable-with="Add New Item" onclick="AddItem();">
    </div>
  </fieldset>

  <br>
  <%- begin %>
    <%- column = @claim.meta["tables"].first.keys %>

    <div id="items-container">
      <div class="items">
        <h3>Room: (living Room)</h3>
        <table>
          <tr>
            <%- ["DESCRIPTION", "QUANTITY", "UNIT", "PRICE"].each do |key| %>
              <th>
                <%= key.upcase %>
              </th>
            <%- end %>
          </tr>
          <tr>
            <td>Remove and Reset Contents</td>
            <td></td>
            <td>1</td>
            <td>$500.00</td>
            <td onclick="removeItem(this);" style="cursor: pointer;color: red;">&#9003;</td>
          <tr>
        </table>
      </div>
    </div>

    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      .attributes_table table td {
        padding: 0;
        padding-top: 5px;
        padding-bottom: 5px;
      }

      .items {
        padding-bottom: 8px;
      }

    </style>

  <%- rescue %>
    <p>Data not found.</p>
  <%- end %>


</form>

<br>
<hr>
<br>
<div class="buttons" style="float: right;">
  <a href="<%= export_claim_url(format: :pdf) %>" target="_blank" id="save-review">
    <input type="submit" name="commit" value="Save & Export" data-disable-with="Save & Export">
  </a>
</div>

<script src="/js/jquery-3.5.1.min.js"></script>

<script type="text/javascript">
  function AddItem() {
    name     = document.getElementById('item-name').value;
    desc     = document.getElementById('item-desc').value;
    quantity = document.getElementById('item-quantity').value;
    unit     = document.getElementById('item-unit').value;
    price    = document.getElementById('item-price').value;
    // acv      = document.getElementById('item-acv').value;
    // rcv      = document.getElementById('item-rcv').value;

    html = `<tr>
              <td>${desc}</td>
              <td>${quantity}</td>
              <td>${unit}</td>
              <td>${price}</td>
              <td onclick="removeItem(this);" style="cursor: pointer;color: red;">
                &#9003;
              </td>
            </tr>`;

    item = findOrCreateItems(name);
    item.lastElementChild.innerHTML += html;
  }

  function findOrCreateItems(text){
    items = document.getElementsByClassName('items');
    newItem = true;

    for (var i=0; i<items.length; i++) {
      if (items[i].firstElementChild.textContent.trim() == text.trim()) {
        newItem = false;
        return items[i];
      }
    }

    if (newItem == true) {
      html = `<div class="items">
                <h3>${text}</h3>
                <table>
                  <tbody>
                    <tr>
                      <th>DESCRIPTION</th>
                      <th>QUANTITY</th>
                      <th>UNIT</th>
                      <th>PRICE</th>
                    </tr>
                  </tbody>
                </table>
              </div>`;

      container = document.getElementById('items-container');
      container.innerHTML += html;
    }

    AddItem();
  }

  function removeItem(el) {
    el.parentNode.remove();
  }

  function tableToJSON(){
    items    = []
    items_el = document.getElementsByClassName('items');
    table    = items_el[0].lastElementChild;

    for (var i=1; i<table.rows.length; i++) {
      if (table.rows[i].textContent.trim() != "") {
        c = {
          description: table.rows[i].cells[0].textContent,
          quantity: table.rows[i].cells[1].textContent,
          unit: table.rows[i].cells[2].textContent,
          price: table.rows[i].cells[3].textContent
        };

        items.push(c);
      }
    }

    return items;
  }

  $("#save-review").click(function(){
    json_data = tableToJSON();
    $.post("<%= review_claim_url(claim) %>",
      {
        data: json_data
      });
  });
</script>

app/views/admin/claims/meta.html.erb
<%- begin %>
  <%- column = @meta["tables"].first.keys %>

  <table>
    <tr>
      <th></th>
      <%- column.each do |key| %>
        <th>
          <%= key.upcase %>
        </th>
      <%- end %>
    </tr>
    <%- @meta["tables"].each_with_index do |row, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <%- column.each do |key| %>
        <td>
          <%= row[key] %>
        </td>
        <%- end %>
      <tr>
    <%- end %>
  </table>

  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    tr:first-child {background: #dddddd}
  </style>

<%- rescue %>
  <p>Data not found.</p>
<%- end %>